version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - poetry-{{ checksum "poetry.lock" }}
      - run: poetry install
      - save_cache:
          key: poetry-{{ checksum "poetry.lock" }}
          paths:
            - .venv
      - run: poetry run pytest
      - run: poetry run flake8 sql_athame tests
      - run: poetry run mypy sql_athame/**.py tests/**.py
      - run: poetry run black --check sql_athame tests
      - run: poetry run isort --check-only sql_athame/**.py tests/**.py
      - store_test_results:
          path: results
      - store_artifacts:
          path: results/pytest/cov_html
          destination: pytest-coverage
      - run: poetry build
      - persist_to_workspace:
          root: ./dist
          paths:
            - "*"
  publish:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - attach_workspace:
          at: ./dist
      - run: poetry publish --repository testpypi

workflows:
  main:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - build-and-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
