version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:latest
      - image: postgres:12
        environment:
          POSTGRES_PASSWORD: password

    steps:
      - checkout
      - restore_cache:
          keys:
            - poetry-{{ checksum "poetry.lock" }}
      - run: poetry install
      - save_cache:
          key: poetry-{{ checksum "poetry.lock" }}
          paths:
            - .venv

      - run:
          command: poetry run flake8 sql_athame tests
          when: always
      - run:
          command: poetry run mypy sql_athame/**.py tests/**.py
          when: always
      - run:
          command: poetry run black --check sql_athame tests
          when: always
      - run:
          command: poetry run isort --check-only sql_athame/**.py tests/**.py
          when: always
      - run:
          command: poetry run pytest
          when: always

      - store_test_results:
          path: results
      - store_artifacts:
          path: results/pytest/cov_html
          destination: pytest-coverage

      - run: poetry build

      - persist_to_workspace:
          root: ./dist
          paths:
            - "*"

  publish:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - attach_workspace:
          at: ./dist
      - run: poetry publish

workflows:
  main:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - build-and-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
