name: publish

on:
  push:
    tags:
      - 'v**'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      UV_PUBLISH_TOKEN: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.6"
          enable-cache: true
          python-version: '3.12'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: uv build
      - run: uv publish
