name: test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    strategy:
      matrix:
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
    env:
      PGPORT: 5432
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.6"
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - run: uv sync
      - run: uv run ruff check
      - run: uv run ruff format --diff
        if: success() || failure()
      - run: uv run mypy sql_athame/**.py tests/**.py
        if: success() || failure()
      - run: uv run pytest
        if: success() || failure()
